name: Hearty
favicon: null
layout_spectrum: 0.23132
typography_spectrum: 0.24859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f03d6b'
    - '#000000'
    - '#800000'
    - '#ffffff'
    - '#808080'
  brandStrength: 0
  lightness: 1
  saturation: 0.024938678136095405
  rhythmicContrast: 0.75
purpose: []
