name: Hearty
favicon: null
layout_spectrum: 0.13292208244092762
typography_spectrum: 0.8606861375737935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09646178735420108
  lightness: 0.6855616124812514
  saturation: 0.024938678136095405
  rhythmicContrast: 0.7893296724651009
purpose: []
